# Generated by Django 4.2.4 on 2023-08-17 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
